[tool.poetry]
name = "leetcode"
version = "1.0.0"
description = "Notes on LeetCode problem solving and basics of algorithm."
authors = ["Satoshi Jek <jks15satoshi@gmail.com>"]
license = "CC-BY-4.0"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
mkdocs = "^1.2.3"
mkdocs-material = "^8.2.4"
mkdocs-exclude = "^1.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
